
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonaServiceImpService", targetNamespace = "http://servicio.java.casa.org.ar/", wsdlLocation = "http://localhost:8080/PersonaServiceImpService/PersonaServiceImp?wsdl")
public class PersonaServiceImpService
    extends Service
{

    private final static URL PERSONASERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONASERVICEIMPSERVICE_EXCEPTION;
    private final static QName PERSONASERVICEIMPSERVICE_QNAME = new QName("http://servicio.java.casa.org.ar/", "PersonaServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PersonaServiceImpService/PersonaServiceImp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONASERVICEIMPSERVICE_WSDL_LOCATION = url;
        PERSONASERVICEIMPSERVICE_EXCEPTION = e;
    }

    public PersonaServiceImpService() {
        super(__getWsdlLocation(), PERSONASERVICEIMPSERVICE_QNAME);
    }

    public PersonaServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONASERVICEIMPSERVICE_QNAME, features);
    }

    public PersonaServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, PERSONASERVICEIMPSERVICE_QNAME);
    }

    public PersonaServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONASERVICEIMPSERVICE_QNAME, features);
    }

    public PersonaServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonaServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonaServiceWs
     */
    @WebEndpoint(name = "PersonaServiceImpPort")
    public PersonaServiceWs getPersonaServiceImpPort() {
        return super.getPort(new QName("http://servicio.java.casa.org.ar/", "PersonaServiceImpPort"), PersonaServiceWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonaServiceWs
     */
    @WebEndpoint(name = "PersonaServiceImpPort")
    public PersonaServiceWs getPersonaServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.java.casa.org.ar/", "PersonaServiceImpPort"), PersonaServiceWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONASERVICEIMPSERVICE_EXCEPTION!= null) {
            throw PERSONASERVICEIMPSERVICE_EXCEPTION;
        }
        return PERSONASERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
